export async function generateMetadata({
  params,
}: {
  params: { mark: string };
}) {
  const mark = params.mark.toUpperCase().replaceAll('-', ' ');

  return {
    title: `${mark} - King vapes - Pod descartável, vapes e muito mais!`,
    // description: "Generated by create next app",
  };
}

import SubMark2 from '@/components/menu/mark/subMark2';

export default async function Page({ params }: { params: { mark: string } }) {
  const mark = params.mark.toUpperCase().replaceAll('-', ' ');

  return (
    <SubMark2
      markLink={{
        url: '/marcas',
        title: 'Marcas',
      }}
      markTitle={mark}
    />
  );
}
