import { Metadata } from 'next';

import SpecialOffers from '@/components/menu/special-offers';

export const metadata: Metadata = {
  title:
    'Ofertas especiais - promoções - King vapes - Pod descartável, vapes e muito mais!',
  // description: "Generated by create next app",
};

export default async function Page() {
  return <SpecialOffers specialOffersTitle="PROMOÇÕES" />;
}
